name: "build-images"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - 'master'
    - 'arm'

jobs:
  all-image-build-success:
    needs:
    - docker-build
    runs-on: ubuntu-latest
    steps:
    - run: echo success
  docker-build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            image:
            - figlet
            - jq
    steps:
    - uses: actions-go/modified@master
      id: is-modified
      with:
        pattern: ${{ matrix.image }}/**
    - uses: actions/checkout@v1
      if: steps.is-modified.outputs.modified == 'true' || (github.event_name == 'push' && github.event.ref == 'refs/heads/arm')
    - run: |
        echo ::group::build image ${{ matrix.image }}:latest
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t ${{ matrix.image }} ${{ matrix.image }}
        echo ::endgroup::
        if [ -e "${{ matrix.image }}/tags.yaml" ]; then
          for tag in $(cat "${{ matrix.image }}/tags.yaml" | docker run --rm -i whalebrew/yq  -r '.versions[]'); do
            echo ::group::build image ${{ matrix.image }}:${tag}
              docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t ${{ matrix.image }}:${tag} --build-arg VERSION=${tag} ${{ matrix.image }}
            echo ::endgroup::
          done
        fi
      if: steps.is-modified.outputs.modified == 'true' || (github.event_name == 'push' && github.event.ref == 'refs/heads/arm')
